name: dispatch-web-deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.QUARTZ_TOKEN }}
          repository: polymathic-institute/polybok-web
          event-type: repository_dispatch
